# Generated by Django 5.1 on 2024-09-09 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category'),
        ),
    ]
